# Generated by Django 5.1.6 on 2025-02-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.JSONField(default=list)),
                ('player_x', models.CharField(max_length=50)),
                ('player_o', models.CharField(max_length=50)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
