# Generated by Django 5.1.7 on 2025-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('identifier', models.CharField(max_length=100)),
                ('script_file', models.CharField(help_text='Path to game JS file in /static/js/', max_length=200)),
            ],
        ),
    ]
